### ISSUE TITLE
DropboxManager not working with latest esp8266 Community release 2.5.0 in Arduino IDE

### ISSUE THREAD

**Issue by jplavoiemtl** [lucasromeiro/DropboxManager#2]
Dropbox Manager stopped working for me when I updated to the latest esp8266 Community version 2.5.0 of board manager in Arduino IDE.  I got Error message when trying to upload a file to DropBox in my skectch and a FAIL when trying to get a new token.  I reverted to esp8266 Community version 2.4.2 and everything is working fine with Dropbox Manager.  Is it possible for you to fix it?  Thanks.

**Comment by lucasromeiro** [comment]
> Dropbox Manager stopped working for me when I updated to the latest esp8266 Community version 2.5.0 of board manager in Arduino IDE. I got Error message when trying to upload a file to DropBox in my skectch and a FAIL when trying to get a new token. I reverted to esp8266 Community version 2.4.2 and everything is working fine with Dropbox Manager. Is it possible for you to fix it? Thanks.

Hello, thank you for reporting the problem!
We are glad you are using our library!
I hope she's helping out.
Could you give us more details of the errors that occur?
If possible, turn on the DEBUG mode and send us here all the errors you have found to facilitate the correction.
As soon as possible we will make this adjustment!
Thanks!!

**Comment by AAJAY5** [comment]
I having solution for the  latest esp8266 Community version 2.5.0 may i change or get repo access
.

**Comment by Amrutha-bv** [comment]
I am facing the same issue. I tried the solution suggested by AAJAY5. I only get FAIL error while trying to generate the token. Using latest ESP8266 board, version 2.7.0. 

I did revert to version 2.4.2to check whether token is generated. I get this error while I run the code

> Connecting to Dropbox...
> Certificate matches!
> Request sent!

> FAIL
>
