### ISSUE TITLE
Multiple files via multiples devices

### ISSUE THREAD

**Issue by Schaggo** [lucasromeiro/DropboxManager#4]
Your project is awesome! 

I am currently working on a esp32 camera array that takes a picture via Blynk and then uploads each picture taken to a free web host. 
I am currently running into an upload limit that lets me only place 4 filed simultaneously. 
Might DropboxManager work?

Cheers
Marco

**Comment by lucasromeiro** [comment]
> Your project is awesome!
> 
> I am currently working on a esp32 camera array that takes a picture via Blynk and then uploads each picture taken to a free web host.
> I am currently running into an upload limit that lets me only place 4 filed simultaneously.
> Might DropboxManager work?
> 
> Cheers
> Marco

Thanks.

I have never done this test, but I believe there is no problem using it on multiple devices.

I never tested the code on esp 32, only esp 8266.
It needs to be tested too.
