### ISSUE TITLE
The example works for me with short text files < about 6k, but fails on larger files

### ISSUE THREAD

**Issue by bmillier** [lucasromeiro/DropboxManager#5]
I am trying to use your library and example code. But, instead of clicking on the link you gave where Dropbox supplies a user code, and then getting a token using your "getToken()", I just created my own Dropbox program, and used the token that it gave me when I clicked the "generate token" button.
If I paste that into the example program, it works fine with the short test.txt file. I've also gotten it to work with text files of 3000- 5000 chars, but no files larger than that work, nor do other types of files such as JPG (50-150K in length). When I activate debug, I see the message that the Certificate doesn't match, but it still sends those short .txt files OK. This certificate mismatch must have something to do with the fingerprint constant, embedded in your library, not matching my Dropbox "app" (although I don't see where that is ever supplied by Dropbox)
 If I patch in some debug code to print the variable "index" in your .cpp file, I can see each 1000 byte packet being sent. At the end of the transfer however, it seems to wait for a response from Dropbox for a while, then returns the "ERROR!" message.
  I next tried to follow the link in your docs , get a 43 char user ID, and then call the getToken() routine with that user ID.  Next I insert that token in the begin() routine, and  print it to Serial console. The first time, it returned a proper token, but it still wouldn't send those larger files mentioned above. The second time I ran the sketch, it just gave me a FAIL for the token. 
  Is there something I am missing? The sketch always sends a short text message and NEVER sends the longer files, whether I use my own token, or the one derived from that link you provide to Dropbox.
Any help would be appreciated.

**Comment by lucasromeiro** [comment]
Hello, thanks for the feedback with more details!
They had never reported this kind of error!
It is something new for me!
Theoretically the file size should not influence anything in the upload, except for mega files. For them there is a different method. I suppose Dropbox has changed something in its API and the library is out of date from these likely changes.
Because I have never received such a problem and in my tests I did not find this problem either.

**Comment by lucasromeiro** [comment]
When uploading files that contain 0x00 bytes as JPEG photos the code identifies as a finisher character and does not send the file correctly. Thanks for finding the problem and letting me know by email!
I will correct as soon as possible!
